### ISSUE TITLE
Failed to minify the code

### ISSUE THREAD

**Issue by alossar** [pusher/chatkit-client-js#59] opened 2018-03-22 18:19 UTC
Hi, I'm having issues creating a build with React.
`react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/@pusher/chatkit/es.js:3

Read more here: http://bit.ly/2tRViJ9`

**Comment by callum-oakley** [comment] 2018-03-26 10:26
Hi @alossar,

How are you importing chatkit? You should be able to use `@pusher/chatkit/react-native` to point to a precompiled react native build?

**Comment by lukejacksonn** [comment] 2018-03-26 10:27
It looks like you are trying to import the es module, not the umd bundle. Is this intentional? What does your import statement look like?

It should look like `import { ChatManager } from '@pusher/chatkit'` which should point at a bundle that has already been minified by us.

**Comment by alossar** [comment] 2018-03-27 13:43
Hi! My import looks like this `import Chatkit from '@pusher/chatkit'`
I had to downgrade from `"@pusher/chatkit": "^0.7.4",` to `"@pusher/chatkit": "^0.7.1",` to be able to build

**Comment by callum-oakley** [comment] 2018-03-29 08:22
@alossar Interesting, your minifier shouldn't care about the `es.js` file... it's only used if you import as an ES6 module. I'm not super familiar with the react build scripts but is there some way of explicitly setting files to ignore as a workaround? (Or even just deleting the `es.js` file, though neither of these are a permanent fix!)

@lukejacksonn the demo app is building with `react-scripts build` right? You on the version with the ES6 module?

**Comment by lukejacksonn** [comment] 2018-03-29 13:35
The demo uses `create-react-app` which does use `react-scripts build` I believe. It currently uses `@pusher/chatkit` version `0.7.3` with no issues.

**Comment by harrisrobin** [comment] 2018-03-29 23:54
I can confirm that this works on 0.7.3 and i had to downgrade from 0.7.5 for it to work.

**Comment by callum-oakley** [comment] 2018-04-03 11:31
@alossar @harrisrobin It looks like `react-scripts` will try to use the `module` field in `package.json` but expects it to be fully ES5 (apart from the module syntax). 0.7.7 should hopefully fix this for you.

Thanks for letting us know of the issue! I'll close this optimistically... let me know if 0.7.7 doesn't do the trick and we'll re-open :)

**Closed by callum-oakley** 2018-04-03 11:31 UTC

**Comment by karankapur999** [comment] 2019-12-16 10:43
@callum-oakley This issue still exists in the latest versions of Pusher
