### ISSUE TITLE
File is owned by another user_id

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#82] opened 2018-06-13 17:45 UTC
Good day guys, when i attach same file as i did before i got error: File is owned by another user_id: my_id. More information can be found at https://docs.pusher.com/errors/services/chatkit_files/bad_request/user_not_file_owner
Its my fault or not?

**Comment by alexey13** [comment] 2018-06-13 17:50
To be clear what is happen. I attach file. After i attach same file from account of another user (same computer) and got that error.

**Comment by mdpye** [comment] 2018-11-05 16:42
This is (I believe) the intended behaviour of the current API. You would need to re-upload the content under the new user.

The main motivation for this is (GDPR) user deletion. If we are asked to delete a user, we need to delete all the content they uploaded, and this is much more reliable if each file upload has exactly one owner.

I'm going to close this issue as it's been a long time and we are planning a refresh of how message attachments work and deprecating the old Files API (which we did not bring out of beta with the rest of the service).

**Closed by mdpye** 2018-11-05 16:42 UTC
