### ISSUE TITLE
First room presence undefined

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#60] opened 2018-03-25 15:36 UTC
Hi guys! Looks like a bug. Can you confirm?
Scenario. User create room and add another user to that room. Second user online and subscribe to it. 
```
onAddedToRoom: room => {
  console.log(room.users.map(x => x.presence))
}
```

Problem. In console i see undefined as object presence of user that created room.

```
[
  {
    "lastSeenAt": null,
    "state": "online",
    "userId": "man"
  },
  undefined
]
```

If user already had a room with same user in session before - no errors. Undefined will gone after user that created a room refresh page.

**Comment by callum-oakley** [comment] 2018-03-26 10:22
Thanks for letting us know @alexey13. I think I can see what would cause this to happen, but it'll take a little bit of investigation to patch it up. Will keep you updated.

In the meantime you'll have to check that presence isn't `undefined`...sorry about that!

**Comment by alexey13** [comment] 2018-03-26 12:00
Thanks Callum! Need it t0 check online user or not, will wait

**Comment by callum-oakley** [comment] 2018-04-03 16:05
@alexey13 You shouldn't see presence `undefined` any more in `0.7.7` :) I'm going to close this optimistically, but feel free to re-open if this doesn't fix things for you!

**Closed by callum-oakley** 2018-04-03 16:05 UTC

**Comment by alexey13** [comment] 2018-04-06 20:10
Callum now unknown, thanks, but i cant get presense.state of user because unknown means offline and online at same time. Only when user close tab presense.state get status. I check presense.state and if its offline massage sent by email.

**Comment by alexey13** [comment] 2018-04-07 07:48
I can add presence state on client side by using hooks. For example addedtoRomm => online('userThatCreatedRoom'). And on side of user that created room createRoom.then(online('currentUser'))

**Comment by callum-oakley** [comment] 2018-04-09 15:37
@alexey13 I managed to reproduce this my end, it looks like a bug server side. Will try and get that fixed up ASAP, thanks for letting us know!

**Comment by alexey13** [comment] 2018-04-10 06:14
@callum-oakley thanks!
