### ISSUE TITLE
Presence state 

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#162] opened 2019-04-27 05:42 UTC
Good day, guys! Is it possible to get presence state of the user that we do not share a room? By client js sdk or server side php sdk? I saw that one and tried to subscribe from client but its not working https://pusher.com/docs/chatkit/reference/presence need to use it from server sdk? Use case - show status of a user(s) before we create a room

**Comment by alexey13** [comment] 2019-07-27 20:28
Hi! Any ideas on this one?

**Comment by joshmaines** [comment] 2019-08-21 14:04
Have the users join a room together and have separate rooms as well. You can then have them check the shared channel for other users' states. Alternatively, you can code a connect/disconnect private channel if you have a ton of users and just use that to update the connection status of users but not the disconnect and then expire their connections after a while.

**Comment by minaorangina** [comment] 2020-03-06 14:28
Hi, this isn't something we support right now, I'm adding it as a feature request

**Comment by minaorangina** [comment] 2020-03-06 15:22
Duplicate of #208, will close this one

**Closed by minaorangina** 2020-03-06 15:22 UTC
Labels: feature request
