### ISSUE TITLE
setReadCursor takes too long

### ISSUE THREAD

**Issue by zoozalp** [pusher/chatkit-client-js#173] opened 2019-05-20 16:35 UTC
When I'm trying to update my read cursor, it takes about 1 minute and 15 seconds to get a response. Is it a temporary server issue or am I missing something?

`currentUser.setReadCursor({roomId, position})
                .then(() => console.log("Updated read cursor", roomId, position));`

**Comment by zoozalp** [comment] 2019-05-20 17:04
By the way, I've just noticed that it updates instantly in iOS. The problem appears to be in Android only.

**Comment by eugenCodreanu** [comment] 2019-08-07 18:03
Hi today I noticed that setReadCursor kill the Chat listener....after applying setReadCursor ....onRoomUpdated doesn't fire anymore.....problem is only on Android ( 
Do you know that can be the problem?

**Comment by callum-oakley** [comment] 2019-08-08 08:35
If this is a problem only with Android, can you please make an issue on the Android SDK? Closing this on the assumption that the issue is with the Android SDK not the Javascript SDK.

**Closed by callum-oakley** 2019-08-08 08:35 UTC
