### ISSUE TITLE
Issue with importing 

### ISSUE THREAD

**Issue by gruntday** [pusher/chatkit-client-js#127] opened 2019-01-01 11:31 UTC
Hello,

Got below error when trying to import the library

`import { ChatManager, TokenProvider } from '@pusher/chatkit-client/react-native';`

Error:

Error:(5, 44) TS7016: Could not find a declaration file for module '@pusher/chatkit-client/react-native'. '/node_modules/@pusher/chatkit-client/react-native.js' implicitly has an 'any' type.
  Try `npm install @types/pusher__chatkit-client` if it exists or add a new declaration (.d.ts) file containing `declare module 'pusher__chatkit-client';`

**Comment by hamchapman** [comment] 2019-01-02 11:42
We don't have typings for the SDK right now. I'm surprise that the absence of a typings file for the SDK is leading to an actual error. Do you have some sort of strict typings rule enabled? If so, you'll need to disable it for the Chatkit SDK

**Comment by CloCloCola** [comment] 2019-01-08 09:16
Hi, I'm also receiving this error. I've checked the project and have no strict typing rules enabled.
I'm following the slack clone tutorial (https://github.com/pusher/build-a-slack-clone-with-react-and-pusher-chatkit#step-1-download-the-react-starter-template) using the cloned repo, and am unable to use any of the chatkit client functions because of this. Is there anything else this could be?

**Comment by hamchapman** [comment] 2019-01-08 14:05
@CloCloCola are you also using TypeScript?

**Comment by newtonmathias** [comment] 2019-01-09 18:47
i also get this error when i try importing
import { ChatManager, TokenProvider } from '@pusher/chatkit-client';

Could not find a declaration file for module '@pusher/chatkit-client'. 'c:/Users/admin/Documents/React_chat_app/node_modules/@pusher/chatkit-client/dist/web/chatkit.js' implicitly has an 'any' type.
  Try `npm install @types/pusher__chatkit-client` if it exists or add a new declaration (.d.ts) file containing `declare module '@pusher/chatkit-client';`ts(7016)

**Comment by hamchapman** [comment] 2019-01-11 10:37
I believe that the problem will be because in your TypeScript compiler config you have `noImplicitAny` set to `true`. See here for more info about the compiler options: https://www.typescriptlang.org/docs/handbook/compiler-options.html

Right now there aren't typings that we provide for the SDK so you'll need to set that compiler flag to `false` (or leave it as the default, which appears to be `false`)

**Comment by gruntday** [comment] 2019-01-28 12:55
Thanks @hamchapman setting noImplicitAny to false solved the issue

**Comment by vishwa3** [comment] 2019-06-28 08:43
I am also getting the same error and I am not using Typescript

**Comment by kieranogrady** [comment] 2019-07-23 16:14
I also see a similar import error on v1.7.0+ of SDK, and I'm not using typescript.
This import statement:
```
import { ChatManager, TokenProvider } from '@pusher/chatkit-client';
```
yields this output in webpack-dev-server:
```
"export 'ChatManager' was not found in '@pusher/chatkit-client'
"export 'TokenProvider' was not found in '@pusher/chatkit-client'
```

For now I've worked around the issue by using CommonJS style require:
```
const { ChatManager, TokenProvider } = require('@pusher/chatkit-client');
```

**Comment by MJay2799** [comment] 2019-08-13 14:48
hey @kieranogrady did you find a way to solve this, I'm running through same issue and it is eatiing my head since so if you came across any solution please let me know.

**Comment by kieranogrady** [comment] 2019-08-13 15:59
> hey @kieranogrady did you find a way to solve this, I'm running through same issue and it is eatiing my head since so if you came across any solution please let me know.

Hi @MJay2799, I haven't yet solved this issue unfortunately - I'm still using 1.6.1. I just tried installing 1.11.0 and it still throws the same error reported above.

**Comment by TheUrbina20** [comment] 2019-12-31 18:16
Same here. I'm using version 1.13.3 on Rails 6
Added with yarn and importing as documentation says:

`import { ChatManager, TokenProvider } from '@pusher/chatkit-client';`

And just receive:

```
chatkit.js:24 Uncaught TypeError: Cannot set property 'Chatkit' of undefined
    at chatkit.js:24
    at Module.<anonymous> (chatkit.js:25)
    at Module../node_modules/@pusher/chatkit-client/dist/web/chatkit.js (chatkit.js:5294)
    at __webpack_require__ (bootstrap:19)
    at Module../app/javascript/controllers/chat_controller.js (controllers sync _controller\.js$:32)
    at __webpack_require__ (bootstrap:19)
    at webpackContext (controllers sync _controller\.js$:17)
    at definitionForModuleWithContextAndKey (index.js:9)
    at index.js:3
    at Array.map (<anonymous>)
```

If I instead use the script tag, it works fine.
@kieranogrady did you solve it?

**Comment by callum-oakley** [comment] 2020-03-06 11:42
Closing this because as far as I can see the initial issue raised is solved, and the later comments are unrelated. If anyone is still having import issues, please [contact support](mailto:support@pusher.com) with more details or a minimal reproduction.

**Closed by callum-oakley** 2020-03-06 11:42 UTC
