### ISSUE TITLE
SyntaxError: Unexpected token u in JSON

### ISSUE THREAD

**Issue by iMerica** [pusher/chatkit-client-js#25] opened 2018-02-01 15:35 UTC
Hi,

I received 4 Sentry errors on Chatkit.JS this morning. 

Relevant Breadcrumbs:
-  GET `https://us1.pusherplatform.io/services/chatkit_cursors/v1/<app>/cursors/0/users/<user> ` (HTTP 503 response)
- SyntaxError: Unexpected token u in JSON at position 0 on line 2303 of Chatkit.JS

<img width="883" alt="screen shot 2018-02-01 at 10 34 21 am" src="https://user-images.githubusercontent.com/487897/35686975-8d7854ec-073b-11e8-8df9-76ec11f2e1e8.png">

**Comment by hot-leaf-juice** [comment] 2018-02-02 15:59
Thanks for reporting this! The 503s were likely caused by some brief service downtime, but we should be catching and properly logging this error! Fixed by #27, which I'll try to get merged and released asap.

**Comment by hot-leaf-juice** [comment] 2018-02-05 10:04
Fix merged in 0.6.2 :)

**Closed by hot-leaf-juice** 2018-02-05 10:04 UTC
