### ISSUE TITLE
Taking long time to get user details

### ISSUE THREAD

**Issue by JeevanJain** [pusher/chatkit-client-js#147] opened 2019-02-15 04:41 UTC
[https://us1.pusherplatform.io/services/chatkit/v/x-x-x-x/users_by_ids?id=6](https://us1.pusherplatform.io/services/chatkit/v/x-x-x-x/users_by_ids?id=6 )
api is taking around 2 sec some times and stopping application.

**Comment by 3ur3ka** [comment] 2019-02-19 11:55
I'm experiencing the same issue, something seems to be blocking the main thread when the client calls users_by_ids which for me takes about 10 sec.
Here is the code I am using to connect:

    const tokenProvider = new Chatkit.TokenProvider({
      url: process.env.REACT_APP_CHATKIT_TEST_TOKEN_URL,
    });

    const chatManager = new Chatkit.ChatManager({
      instanceLocator: process.env.REACT_APP_CHATKIT_INSTANCE_LOCATOR,
      userId: 'Dave',
      tokenProvider: tokenProvider,
    });

    chatManager
      .connect({
        onUserStartedTyping: this.actions.isTyping,
        onUserStoppedTyping: this.actions.notTyping,
        onAddedToRoom: this.actions.subscribeToRoom,
        onPresenceChanged: this.actions.setUserPresence,
      })
      .then(user => {
        // Subscribe to all rooms the user is a member of
        Promise.all(
          user.rooms.map(room =>
            user.subscribeToRoom({
              roomId: room.id,
              hooks: { onMessage: this.actions.addMessage },
            }),
          ),
        ).then(rooms => {
          this.actions.setUser(user);
          // Join the first room in the users room list
          user.rooms.length > 0 && this.actions.joinRoom(user.rooms[0]);
        });
      })
      .catch(error => console.log('Error on connection', error));

**Comment by JeevanJain** [comment] 2019-02-19 13:34
+1

**Comment by callum-oakley** [comment] 2019-02-19 13:51
I'm not sure what could be causing the main thread to be blocked (everything is asynchronous internally). Do either of you have a reproduction which shows this happening?

**Comment by 3ur3ka** [comment] 2019-02-21 05:30
I made a repo here: [https://github.com/3ur3ka/chatkit-demo](https://github.com/3ur3ka/chatkit-demo)

Seems as if something is waiting for the websocket to be established (e.g. you can't click the 'learn react' link until the websocket is alive...)

Many Thanks!

**Comment by callum-oakley** [comment] 2019-02-21 10:36
Hmmm, @3ur3ka thanks for the repo, I'm having trouble reproducing the delay though. It loads pretty snappily for me! I did a little bit of profiling with the chrome performance tools (we're running the same version of chrome 😉) and the initial load seems to be happening before users_by_ids is even called? 

What version of the SDK are you using? Could you try running a performance profile (performance tab in the chrome dev tools) and posting a screenshot? Cheers.

**Comment by 3ur3ka** [comment] 2019-02-21 10:52
Hi Callum, thanks for testing, here are the screenshots, not sure if I'm capturing the right info though,

![screen shot 2019-02-21 at 10 48 19](https://user-images.githubusercontent.com/6122193/53163636-738e1980-35c6-11e9-8226-f99f4de524c7.png)


![screen shot 2019-02-21 at 10 47 17](https://user-images.githubusercontent.com/6122193/53163616-640ed080-35c6-11e9-9424-434a8f89fc83.png)

**Comment by 3ur3ka** [comment] 2019-02-21 10:53
can I pm you my keys and then perhaps you can see the problem? (They're only test keys..)

**Comment by callum-oakley** [comment] 2019-02-21 11:06
Sure! The best way is probably to ping a message to support@pusher.com with them and let them know you've been speaking to me here.

**Comment by callum-oakley** [comment] 2019-02-21 11:57
Got your email, thanks. Looks to be the same issue as this: https://github.com/pusher/react-slack-clone/pull/81

I'm not sure why object-path-immutable is so very slow in this case, but that seems to be the crux of the problem...

**Comment by 3ur3ka** [comment] 2019-02-21 12:03
Great thanks, I'll update the repo and retry when I get back tonight

**Comment by 3ur3ka** [comment] 2019-02-23 09:19
Yes, that's all fixed now, thanks a lot!

**Comment by callum-oakley** [comment] 2019-02-25 09:42
Good to hear. Thanks for following up! 🙂

**Closed by callum-oakley** 2019-02-25 09:42 UTC
